### ISSUE TITLE
Comment on PR / Github PR Review

### ISSUE THREAD

**Issue by hazcod** [sysdiglabs/scan-action#1]
Hi,
Would be very nice to not have to dig into the logs to be able to debug why a build is not working.
In case you don't want to reinvent the wheel, an integration with https://github.com/reviewdog/reviewdog could be possible as wel.

**Comment by Kaizhe** [comment]
@hazcod thanks for the suggestion, it's really a good one. Unfortunately I don't have the bandwidth for it, do you mind to create a PR for it?

**Comment by airadier** [comment]
Hi @hazcod, latest v3 supports SARIF report output and publishes the scan result as a check run with annotations.

Thanks very much for the request!
